name: Auto Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Post automated review
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = [
              'Automated review (baseline checks):',
              '- Fee calc: two-pass exact vsize and feeRate used',
              '- RBF: inputs sequence set to 0xfffffffd',
              '- Dust: change only if > 546 sats',
              '- Logging: estimate vs exact fee and change present'
            ].join('\n');
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              event: 'COMMENT',
              body
            });

